#!/bin/bash
location=''
theme=''
mode=''

help (){
	echo 'usage: solarbg [options]'
	echo 'options:'
	echo '  -m				Wallpaper type(solar,gnome)'
	echo '  -l LAT:LON		        Your location(needed for sun mode)'
	echo '  -t				Theme name(theme path is ~/.local/share/solarbg/themes)'
	echo '  -h				Show this message'
	echo ''
	exit
}

while getopts "m:l:t:h" flag;do
	case $flag in
		"l") location=(${OPTARG//:/ })
		;;
		"m") 
			mode=$OPTARG
		;;
	    "t") 
			theme=$OPTARG 
		;;
		"h")
			help
		;;
    esac	
done

if ( [ ! ${#location[@]} -eq 2 ] && [ "$mode" = 'solar' ] ) || ( [ "$mode" != 'gnome' ] && [ "$mode" != 'solar' ] ) || [ -z $theme ]
then
	help
fi

node --no-warnings /usr/lib/solarbg-git/index.js $mode $theme $(echo "${location[0]}" | bc) $(echo "${location[1]}" | bc)

